#cloud-config
hostname: golf-gui-vm
fqdn: golf-gui-vm.local

users:
  - name: debian
    groups: [adm, sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    hashed_passwd: __DEBIAN_PASSWORD_HASH__
    ssh_authorized_keys:
      - __BUILDER_PUB__

ssh_pwauth: false

package_update: true
packages:
  - curl
  - ca-certificates
